### ISSUE TITLE
Error with cyrillic characters do not raise

### ISSUE THREAD

**Issue by morfair** [crossbario/crossbar#461]
I try to raise error on callee and expect that caller get RPC-call ErrorBack. It work with latin characters in ApplicationError message, but not work with cyrillic characters. It affected after upgrade Crossbar from v0.10 to v0.11.

It work:
```raise ApplicationError(u"com.example.error.form_error", u"Wrong characters count in title")```

It DON'T work:
```raise ApplicationError(u"com.example.error.form_error", u"Неверное кол-во. символов в заголовке")```

-
UPD: I changed code and get error:
```
errmsg = u"Неверное кол-во. символов в заголовке"
print errmsg
raise ApplicationError(u"ru.radpomoch.v2.error.form_error", errmsg)
```
...and got error on callee:
```
2015-09-17T14:58:48+0300 [Controller  16721] Temporarily disabling observer <function StandardOutObserver at 0x19c8758> due to exception: [Failure instance: Traceback: <type 'exceptions.UnicodeEncodeError'>: 'ascii' codec can't encode characters in position 0-7: ordinal not in range(128)
local/lib/python2.7/site-packages/crossbar/controller/processtypes.py:172:log
local/lib/python2.7/site-packages/crossbar/_logging.py:354:_log
local/lib/python2.7/site-packages/twisted/logger/_logger.py:210:info
local/lib/python2.7/site-packages/twisted/logger/_logger.py:132:emit
--- <exception caught here> ---
local/lib/python2.7/site-packages/twisted/logger/_observer.py:131:__call__
local/lib/python2.7/site-packages/crossbar/_logging.py:158:StandardOutObserver
]Traceback (most recent call last):
  File "local/lib/python2.7/site-packages/crossbar/controller/processtypes.py", line 172, in log
    cb_namespace=event_namespace, **event)
  File "local/lib/python2.7/site-packages/crossbar/_logging.py", line 354, in _log
    getattr(self.logger, level)(*args, **kwargs)
  File "local/lib/python2.7/site-packages/twisted/logger/_logger.py", line 210, in info
    self.emit(LogLevel.info, format, **kwargs)
  File "local/lib/python2.7/site-packages/twisted/logger/_logger.py", line 132, in emit
    self.observer(event)
--- <exception caught here> ---
  File "local/lib/python2.7/site-packages/twisted/logger/_observer.py", line 131, in __call__
    observer(event)
  File "local/lib/python2.7/site-packages/crossbar/_logging.py", line 158, in StandardOutObserver
    formatEvent(event))
exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-7: ordinal not in range(128)
```

**Comment by hawkowl** [comment]
Hi @morfair, thanks for reporting this. I've marked it for the 0.11.2 milestone, the next point release we make. Sorry for the trouble!

**Comment by morfair** [comment]
Hi @hawkowl, how long wait 0.11.2?

**Comment by hawkowl** [comment]
@morfair I am hoping next Wednesday at the latest (I'm bundling up a few other bugs for the 0.11.2 maintenance release) -- but I'm hoping I'll have this one fixed in `master` by tomorrow (you could then `pip install https://github.com/crossbario/crossbar/archive/master.zip` then to get a fixed version until it's released)

Thanks for the traceback, it's very helpful!

**Comment by morfair** [comment]
@hawkowl, thank you very much!! Tomorrow commit would be great!! :)

**Comment by morfair** [comment]
UPD: I change code in file `local/lib/python2.7/site-packages/crossbar/_logging.py` at lines 97-99:
```
COLOUR_FORMAT = u"{}{} [{}]{} {}"
NOCOLOUR_FORMAT = u"{} [{}] {}"
SYSLOGD_FORMAT = u"[{}] {}"
```
and `print` began to work good without errors, but caller still doesn't receive neither SuccBac nor ErrBack.

**Comment by alex-eri** [comment]
I suggest to use `from __future__ import unicode_literals` instead of u''

**Comment by hawkowl** [comment]
No, `unicode_literals` should never be used. It causes subtle bugs and removes the distinction of a 'native string' (`print()` takes native strings, unconditionally sending unicode can do weird things).

**Comment by alex-eri** [comment]
Maybe on non utf-8 locales, `print` and `print()` (print function) works fine with unicode.
Adding `u` to  string constants makes is unicode too.

If `unicode_literals` is buggy so `import six`. Providing 2.x compatibility manualy is not good idea i think.

**Comment by oberstet** [comment]
> I suggest to use from __future__ import unicode_literals instead of u''

No.

**Comment by oberstet** [comment]
> Hi @hawkowl, how long wait for the 0.11.2?

Until it's done.

**Comment by morfair** [comment]
Any news?

**Comment by hawkowl** [comment]
@morfair The base issues are fixed in Autobahn/txaio/crossbar, but the prereq Autobahn won't be released for a little while yet (it's in a transitional period). You can install it from `master` and it should work in the meantime, but it may have breaking API changes.

**Comment by hawkowl** [comment]
Hi -- the fixes for Crossbar, Autobahn|Python, and txaio have all landed and the next versions of them should fix this issue up completely

**Comment by morfair** [comment]
When can I start using it completely?

**Comment by goeddea** [comment]
@morfair - as hawkowl said: The fixes are on the current master branch in each case, so if you install from there you can use things immediately.

**Comment by morfair** [comment]
@goeddea, Are you shure? I don't see the appropriate commit, only test changes: https://github.com/crossbario/crossbar/commits/master

**Comment by goeddea** [comment]
@morfair - Sorry for the late response. Have you tested current Crossbar.io to see if the error is still there?

**Comment by morfair** [comment]
@goeddea, yes, i clone current branch with git and bug was.

**Comment by goeddea** [comment]
@morfair - reopened the issue. Could you provide us with a test case (e.g. zipped directory with the minimal code including Crossbar config) that we can use to reproduce your problem?

**Comment by slav0nic** [comment]
@morfair, you must test with latest autobahn from git
here is fix: https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/exception.py#L220-L233
```
In [3]: from autobahn.wamp.exception import ApplicationError

In [6]: try:
    raise ApplicationError(u'Тест')
except ApplicationError as e:
    print(type(e.error), e.error)
   ...:     
(<type 'unicode'>, u'\u0422\u0435\u0441\u0442')
```

**Comment by morfair** [comment]
@slav0nic goood!!! it began to work!! I am very happy!) Now I can continue work.
