### ISSUE TITLE
Authentication "authmethod" and "authextra" arguments not passed to dynamic authorizer function in Crossbar 0.15.0

### ISSUE THREAD

**Issue by marcvdijk** [crossbario/crossbar#911]
Hi,

I have a distributed application that uses crossbar version 0.15.0 installed using pip.
The application uses a dynamic authentication method to handle "ticket" authentication. I recently added "wamp-cra" to this using the same method to process authentication using both auth_methods.

In evaluating which method to handle I was planning to use the "authmethod" and optionally "authextra" key/value pairs in the details dict passed to the custom authenticator function. I however noticed that these are always set to None. 

Switching to crossbar version 0.16.0 from github fixed that issue. That means that whoever uses crossbar 0.15.0 from pip will not be in line with the online documentation or the crossbar examples.
Will these be brought back in sync? version 0.16.x in the python package repository?

**Comment by meejah** [comment]
Basically this bug is saying "please @oberstet make a 0.16.0 release" right?

(But specifically for the authmethod + authextra fixes for wamp-cra in this case)

**Comment by marcvdijk** [comment]
Well, I don't know if my question should be labeled "bug" at all, but yes as the issue is solved in 0.16.0 I would welcome an official release in the python package repository :-).
If the issue I described is actually a bug in the 0.15.0 release, well than it is a bug, difficult for me to judge.

**Comment by hawkowl** [comment]
We have an 0.16 now, please reopen if the version now on PyPI has the same issue.

**Comment by Kolyunya** [comment]
I've just updated both router and client (`autobahn-js`) to the latest versions but still can't get `authextra` from the client. Is there a but in a JS client or am I doing something wrong?
```

         var connection = new autobahn.Connection({
            url: 'ws://127.0.0.1:50000',
            realm: 'my_realm',
            authmethods: ["ticket"],
            authid: principal,
            onchallenge: onchallenge,
            authextra: {
                "foo": "bar"
            }
         });

```

**Comment by oberstet** [comment]
@Kolyunya this is a bug in AutobahnJS that has been resolved on master. I'll do a release today ..

**Comment by Kolyunya** [comment]
@oberstet thank you very much for your work!

**Comment by oberstet** [comment]
@Kolyunya just released AutobahnJS 0.11.2

**Comment by Kolyunya** [comment]
@oberstet great, thank you!
